// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: cabal run skema-generate-config
// Source: Skema.Config.Schema

// ===================================================================
// Config Types
// ===================================================================

export interface LibraryConfig {
  path: string | null;
  watch: boolean;
  auto_scan: boolean;
  auto_scan_interval_mins: number;
  auto_scan_on_startup: boolean;
  normalize_featuring: boolean;
  normalize_featuring_to: string;
  path_format: string;
  file_format: string;
}

export interface SystemConfig {
  watch_config_file: boolean;
  database_path: string | null;
  data_dir: string | null;
  cache_dir: string | null;
}

export interface ServerConfig {
  host: string;
  port: number;
  jwt_secret: string;
  jwt_expiration_hours: number;
  username: string;
  password: string;
}

export interface DownloadConfig {
  nzb_client?: any;
  torrent_client?: any;
  check_interval: number;
  auto_import: boolean;
  min_seeders: number;
  max_size: number;
}

export interface IndexersConfig {
  list: any[];
  search_timeout: number;
}

export interface MusicbrainzConfig {
  server: 'official' | 'headphones_vip' | 'custom';
  custom_url: string;
  username: string;
  password: string;
  album_types: any[];
  exclude_secondary_types: any[];
}

export interface MediaConfig {
  lastfm_api_key: string;
}

export interface NotificationsConfig {
  enabled: boolean;
  providers: any[];
  on_album_found: boolean;
  on_album_downloaded: boolean;
  on_album_imported: boolean;
}


// Full nested config structure (matches backend JSON)
export interface Config {
  library: LibraryConfig;
  system: SystemConfig;
  server: ServerConfig;
  download: DownloadConfig;
  indexers: IndexersConfig;
  musicbrainz: MusicbrainzConfig;
  media: MediaConfig;
  notifications: NotificationsConfig;
}

// ===================================================================
// Schema Metadata (for dynamic form generation)
// ===================================================================

export type FieldType = 'string' | 'path' | 'integer' | 'boolean' | 'enum' | 'list' | 'object';

export interface FieldMeta {
  name: string;
  description: string;
  type: FieldType;
  options?: string[];  // For enum types
  sensitive?: boolean;
  required?: boolean;
}

export interface SectionMeta {
  section: string;
  description: string;
  fields: FieldMeta[];
}

// Schema metadata for each section
export const librarySchema: SectionMeta = {
  section: 'library',
  description: 'Music library configuration',
  fields: [
    {
      name: 'path',
      description: 'Path to music library directory',
      type: 'path'
    }

,
    {
      name: 'watch',
      description: 'Watch library directory for changes',
      type: 'boolean'
    }

,
    {
      name: 'auto_scan',
      description: 'Automatically scan library on interval',
      type: 'boolean'
    }

,
    {
      name: 'auto_scan_interval_mins',
      description: 'Minutes between automatic scans',
      type: 'integer'
    }

,
    {
      name: 'auto_scan_on_startup',
      description: 'Scan library when application starts',
      type: 'boolean'
    }

,
    {
      name: 'normalize_featuring',
      description: 'Normalize featuring artist format in track titles',
      type: 'boolean'
    }

,
    {
      name: 'normalize_featuring_to',
      description: 'Format to use for featuring artists',
      type: 'string'
    }

,
    {
      name: 'path_format',
      description: 'Directory structure format for organizing files',
      type: 'string'
    }

,
    {
      name: 'file_format',
      description: 'File naming format',
      type: 'string'
    }

  ],
};

export const systemSchema: SectionMeta = {
  section: 'system',
  description: 'System and paths configuration',
  fields: [
    {
      name: 'watch_config_file',
      description: 'Watch config file for changes and reload automatically',
      type: 'boolean'
    }

,
    {
      name: 'database_path',
      description: 'SQLite database file path (default: skema.db in data directory)',
      type: 'path'
    }

,
    {
      name: 'data_dir',
      description: 'Data directory override (default: platform-specific)',
      type: 'path'
    }

,
    {
      name: 'cache_dir',
      description: 'Cache directory override (default: platform-specific)',
      type: 'path'
    }

  ],
};

export const serverSchema: SectionMeta = {
  section: 'server',
  description: 'HTTP server configuration',
  fields: [
    {
      name: 'host',
      description: 'Server bind address',
      type: 'string'
    }

,
    {
      name: 'port',
      description: 'Server port',
      type: 'integer'
    }

,
    {
      name: 'jwt_secret',
      description: 'JWT signing secret (auto-generated if not provided)',
      type: 'string',
      sensitive: true
    }

,
    {
      name: 'jwt_expiration_hours',
      description: 'JWT token expiration time in hours',
      type: 'integer'
    }

,
    {
      name: 'username',
      description: 'Username for API authentication (required)',
      type: 'string'
    }

,
    {
      name: 'password',
      description: 'Password for API authentication (required, will be bcrypt hashed)',
      type: 'string',
      sensitive: true
    }

  ],
};

export const downloadSchema: SectionMeta = {
  section: 'download',
  description: 'Download client configuration',
  fields: [
    {
      name: 'nzb_client',
      description: 'NZB download client configuration',
      type: 'object'
    }

,
    {
      name: 'torrent_client',
      description: 'Torrent download client configuration',
      type: 'object'
    }

,
    {
      name: 'directory',
      description: 'Directory for completed downloads (before import)',
      type: 'path'
    }

,
    {
      name: 'check_interval',
      description: 'How often to check for completed downloads (in seconds)',
      type: 'integer'
    }

,
    {
      name: 'auto_import',
      description: 'Automatically import completed downloads',
      type: 'boolean'
    }

,
    {
      name: 'min_seeders',
      description: 'Minimum seeders for torrents (null = no minimum)',
      type: 'integer'
    }

,
    {
      name: 'max_size',
      description: 'Maximum download size in MB (null = no limit)',
      type: 'integer'
    }

  ],
};

export const indexersSchema: SectionMeta = {
  section: 'indexers',
  description: 'Usenet/torrent indexer configuration',
  fields: [
    {
      name: 'list',
      description: 'List of configured indexers',
      type: 'list'
    }

,
    {
      name: 'search_timeout',
      description: 'Search timeout per indexer in seconds',
      type: 'integer'
    }

  ],
};

export const musicbrainzSchema: SectionMeta = {
  section: 'musicbrainz',
  description: 'MusicBrainz metadata provider configuration',
  fields: [
    {
      name: 'server',
      description: 'Which MusicBrainz server to use',
      type: 'enum',
      options: ['official', 'headphones_vip', 'custom']
    }

,
    {
      name: 'custom_url',
      description: 'Custom MusicBrainz server URL (required if server is \'custom\')',
      type: 'url'
    }

,
    {
      name: 'username',
      description: 'Username for authentication (required for Headphones VIP, optional for custom)',
      type: 'string'
    }

,
    {
      name: 'password',
      description: 'Password for authentication (required for Headphones VIP, optional for custom)',
      type: 'string',
      sensitive: true
    }

,
    {
      name: 'album_types',
      description: 'Primary album types to fetch (e.g., Album, EP)',
      type: 'list'
    }

,
    {
      name: 'exclude_secondary_types',
      description: 'Secondary types to exclude (e.g., Live, Compilation)',
      type: 'list'
    }

  ],
};

export const mediaSchema: SectionMeta = {
  section: 'media',
  description: 'Media providers configuration',
  fields: [
    {
      name: 'lastfm_api_key',
      description: 'Last.fm API key for artist images and scrobbling',
      type: 'string',
      sensitive: true
    }

  ],
};

export const notificationsSchema: SectionMeta = {
  section: 'notifications',
  description: 'Notification configuration',
  fields: [
    {
      name: 'enabled',
      description: 'Enable/disable all notifications',
      type: 'boolean'
    }

,
    {
      name: 'providers',
      description: 'List of notification providers',
      type: 'list'
    }

,
    {
      name: 'on_album_found',
      description: 'Send notification when new wanted albums are found',
      type: 'boolean'
    }

,
    {
      name: 'on_album_downloaded',
      description: 'Send notification when albums are downloaded',
      type: 'boolean'
    }

,
    {
      name: 'on_album_imported',
      description: 'Send notification when albums are imported to library',
      type: 'boolean'
    }

  ],
};


export const allSchemas: SectionMeta[] = [
  librarySchema,
  systemSchema,
  serverSchema,
  downloadSchema,
  indexersSchema,
  musicbrainzSchema,
  mediaSchema,
  notificationsSchema
];
