// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: cabal run skema-generate-config
// Source: Skema.Config.Schema

import { PathInput } from './PathInput';
import { UrlInput } from './UrlInput';
import type { Config } from '../types/api';

// ===================================================================
// Field Rendering Component
// ===================================================================

interface FieldProps {
  section: keyof Config;
  field: string;
  value: any;
  onChange: (section: keyof Config, field: string, value: any) => void;
  type: 'string' | 'path' | 'url' | 'integer' | 'boolean' | 'enum';
  description: string;
  options?: string[];
  sensitive?: boolean;
  advanced?: boolean;
  dependsOn?: string;
  dependsOnValue?: { field: string; values: string[] };
  showAdvanced?: boolean;
  sectionValues?: any;
}

function ConfigField({ section, field, value, onChange, type, description, options, sensitive, advanced, dependsOn, dependsOnValue, showAdvanced, sectionValues }: FieldProps) {
  // Hide advanced fields unless showAdvanced is true
  if (advanced && !showAdvanced) return null;
  // Hide fields that depend on another field being truthy
  if (dependsOn && sectionValues && !sectionValues[dependsOn]) return null;
  // Hide fields that depend on another field having specific values
  if (dependsOnValue && sectionValues && !dependsOnValue.values.includes(sectionValues[dependsOnValue.field])) return null;

  const id = `${section}_${field}`;
  const label = field.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

  switch (type) {
    case 'boolean':
      return (
        <div className="flex items-start gap-3">
          <input
            id={id}
            type="checkbox"
            checked={value ?? false}
            onChange={(e) => onChange(section, field, e.target.checked)}
            className="mt-0.5 h-4 w-4 rounded border-dark-border bg-dark-bg-subtle text-dark-accent focus:ring-dark-accent focus:ring-offset-dark-bg-elevated"
          />
          <div>
            <label htmlFor={id} className="text-sm font-medium text-dark-text">{label}</label>
            <p className="text-sm text-dark-text-secondary mt-0.5">{description}</p>
          </div>
        </div>
      );

    case 'integer':
      return (
        <div>
          <label htmlFor={id} className="block text-sm font-medium text-dark-text mb-2">{label}</label>
          <input
            type="number"
            id={id}
            value={value ?? ''}
            onChange={(e) => onChange(section, field, e.target.value ? parseInt(e.target.value) : null)}
            className="input w-48"
          />
          <p className="mt-2 text-sm text-dark-text-secondary">{description}</p>
        </div>
      );

    case 'path':
      return (
        <PathInput
          id={id}
          label={label}
          value={value || ''}
          onChange={(v) => onChange(section, field, v)}
          type="directory"
          description={description}
        />
      );

    case 'url':
      return (
        <UrlInput
          id={id}
          label={label}
          value={value || ''}
          onChange={(v) => onChange(section, field, v)}
          description={description}
          placeholder="localhost:5000"
          defaultProtocol="http://"
          className="w-96"
        />
      );

    case 'enum':
      return (
        <div>
          <label htmlFor={id} className="block text-sm font-medium text-dark-text mb-2">{label}</label>
          <select
            id={id}
            value={value || ''}
            onChange={(e) => onChange(section, field, e.target.value)}
            className="input w-64"
          >
            {options?.map((opt) => (
              <option key={opt} value={opt}>{opt}</option>
            ))}
          </select>
          <p className="mt-2 text-sm text-dark-text-secondary">{description}</p>
        </div>
      );

    default: // string
      return (
        <div>
          <label htmlFor={id} className="block text-sm font-medium text-dark-text mb-2">{label}</label>
          <input
            type={sensitive ? 'password' : 'text'}
            id={id}
            value={value || ''}
            onChange={(e) => onChange(section, field, e.target.value || null)}
            className="input w-64"
          />
          <p className="mt-2 text-sm text-dark-text-secondary">{description}</p>
        </div>
      );
  }
}

// ===================================================================
// Section Components
// ===================================================================

interface LibraryProps {
  config: Config;
  onChange: (section: keyof Config, field: string, value: any) => void;
  showAdvanced?: boolean;
}

export function LibraryConfigSection({ config, onChange, showAdvanced = false }: LibraryProps) {
  const section = config.library;
  return (
    <div className="space-y-6">
      <ConfigField
        section="library"
        field="path"
        value={section.path}
        onChange={onChange}
        type="path"
        description="Path to music library directory"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="watch"
        value={section.watch}
        onChange={onChange}
        type="boolean"
        description="Watch library directory for changes"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="auto_scan"
        value={section.auto_scan}
        onChange={onChange}
        type="boolean"
        description="Automatically scan library on interval"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="auto_scan_interval_mins"
        value={section.auto_scan_interval_mins}
        onChange={onChange}
        type="integer"
        description="Minutes between automatic scans"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="auto_scan_on_startup"
        value={section.auto_scan_on_startup}
        onChange={onChange}
        type="boolean"
        description="Scan library when application starts"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="normalize_featuring"
        value={section.normalize_featuring}
        onChange={onChange}
        type="boolean"
        description="Normalize featuring artist format in track titles"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="normalize_featuring_to"
        value={section.normalize_featuring_to}
        onChange={onChange}
        type="string"
        description="Format to use for featuring artists"
        dependsOn="normalize_featuring"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="path_format"
        value={section.path_format}
        onChange={onChange}
        type="string"
        description="Directory structure format for organizing files"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="file_format"
        value={section.file_format}
        onChange={onChange}
        type="string"
        description="File naming format"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
    </div>
  );
}

interface SystemProps {
  config: Config;
  onChange: (section: keyof Config, field: string, value: any) => void;
  showAdvanced?: boolean;
}

export function SystemConfigSection({ config, onChange, showAdvanced = false }: SystemProps) {
  const section = config.system;
  return (
    <div className="space-y-6">
      <ConfigField
        section="system"
        field="watch_config_file"
        value={section.watch_config_file}
        onChange={onChange}
        type="boolean"
        description="Watch config file for changes and reload automatically"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="system"
        field="database_path"
        value={section.database_path}
        onChange={onChange}
        type="path"
        description="SQLite database file path (default: skema.db in data directory)"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="system"
        field="data_dir"
        value={section.data_dir}
        onChange={onChange}
        type="path"
        description="Data directory override (default: platform-specific)"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="system"
        field="cache_dir"
        value={section.cache_dir}
        onChange={onChange}
        type="path"
        description="Cache directory override (default: platform-specific)"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
    </div>
  );
}

interface ServerProps {
  config: Config;
  onChange: (section: keyof Config, field: string, value: any) => void;
  showAdvanced?: boolean;
}

export function ServerConfigSection({ config, onChange, showAdvanced = false }: ServerProps) {
  const section = config.server;
  return (
    <div className="space-y-6">
      <ConfigField
        section="server"
        field="host"
        value={section.host}
        onChange={onChange}
        type="string"
        description="Server bind address"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="server"
        field="port"
        value={section.port}
        onChange={onChange}
        type="integer"
        description="Server port"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="server"
        field="jwt_secret"
        value={section.jwt_secret}
        onChange={onChange}
        type="string"
        description="JWT signing secret (auto-generated if not provided)"
        sensitive
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="server"
        field="jwt_expiration_hours"
        value={section.jwt_expiration_hours}
        onChange={onChange}
        type="integer"
        description="JWT token expiration time in hours"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="server"
        field="username"
        value={section.username}
        onChange={onChange}
        type="string"
        description="Username for API authentication (required)"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
    </div>
  );
}

interface MusicbrainzProps {
  config: Config;
  onChange: (section: keyof Config, field: string, value: any) => void;
  showAdvanced?: boolean;
}

export function MusicbrainzConfigSection({ config, onChange, showAdvanced = false }: MusicbrainzProps) {
  const section = config.musicbrainz;
  return (
    <div className="space-y-6">
      <ConfigField
        section="musicbrainz"
        field="server"
        value={section.server}
        onChange={onChange}
        type="enum"
        description="Which MusicBrainz server to use"
        options={['official', 'headphones_vip', 'custom']}
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="musicbrainz"
        field="custom_url"
        value={section.custom_url}
        onChange={onChange}
        type="url"
        description="Custom MusicBrainz server URL (required if server is 'custom')"
        dependsOnValue={{ field: "server", values: ["custom"] }}
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="musicbrainz"
        field="username"
        value={section.username}
        onChange={onChange}
        type="string"
        description="Username for authentication (required for Headphones VIP, optional for custom)"
        dependsOnValue={{ field: "server", values: ["headphones_vip", "custom"] }}
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="musicbrainz"
        field="password"
        value={section.password}
        onChange={onChange}
        type="string"
        description="Password for authentication (required for Headphones VIP, optional for custom)"
        sensitive
        dependsOnValue={{ field: "server", values: ["headphones_vip", "custom"] }}
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
    </div>
  );
}

interface MediaProps {
  config: Config;
  onChange: (section: keyof Config, field: string, value: any) => void;
  showAdvanced?: boolean;
}

export function MediaConfigSection({ config, onChange, showAdvanced = false }: MediaProps) {
  const section = config.media;
  return (
    <div className="space-y-6">
      <ConfigField
        section="media"
        field="lastfm_api_key"
        value={section.lastfm_api_key}
        onChange={onChange}
        type="string"
        description="Last.fm API key for artist images and scrobbling"
        sensitive
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
    </div>
  );
}

// ConfigField is not exported with 'export function', so export it here
export { ConfigField };
