// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: cabal run skema-generate-config
// Source: Skema.Config.Schema

import { PathInput } from './PathInput';
import { UrlInput } from './UrlInput';
import type { Config } from '../types/api';

// ===================================================================
// Field Rendering Component
// ===================================================================

interface FieldProps {
  section: keyof Config;
  field: string;
  value: any;
  onChange: (section: keyof Config, field: string, value: any) => void;
  type: 'string' | 'path' | 'url' | 'integer' | 'boolean' | 'enum';
  description: string;
  options?: string[];
  sensitive?: boolean;
  advanced?: boolean;
  dependsOn?: string;
  dependsOnValue?: { field: string; values: string[] };
  showAdvanced?: boolean;
  sectionValues?: any;
}

// Shared visibility rule for a field, reused by group headers so an empty
// group (all fields hidden) does not render a dangling heading.
interface VisibilityMeta {
  advanced?: boolean;
  dependsOn?: string;
  dependsOnValue?: { field: string; values: string[] };
}

function isFieldVisible(meta: VisibilityMeta, sectionValues: any, showAdvanced?: boolean): boolean {
  if (meta.advanced && !showAdvanced) return false;
  if (meta.dependsOn && sectionValues && !sectionValues[meta.dependsOn]) return false;
  if (meta.dependsOnValue && sectionValues && !meta.dependsOnValue.values.includes(sectionValues[meta.dependsOnValue.field])) return false;
  return true;
}

function GroupHeader({ title }: { title: string }) {
  return (
    <div className="border-b border-dark-border pb-2 pt-2">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-dark-text-tertiary">{title}</h3>
    </div>
  );
}

function ConfigField({ section, field, value, onChange, type, description, options, sensitive, advanced, dependsOn, dependsOnValue, showAdvanced, sectionValues }: FieldProps) {
  if (!isFieldVisible({ advanced, dependsOn, dependsOnValue }, sectionValues, showAdvanced)) return null;

  const id = `${section}_${field}`;
  const label = field.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

  switch (type) {
    case 'boolean':
      return (
        <div className="flex items-start gap-3">
          <input
            id={id}
            type="checkbox"
            checked={value ?? false}
            onChange={(e) => onChange(section, field, e.target.checked)}
            className="mt-0.5 h-4 w-4 rounded border-dark-border bg-dark-bg-subtle text-dark-accent focus:ring-dark-accent focus:ring-offset-dark-bg-elevated"
          />
          <div>
            <label htmlFor={id} className="text-sm font-medium text-dark-text">{label}</label>
            <p className="text-sm text-dark-text-secondary mt-0.5">{description}</p>
          </div>
        </div>
      );

    case 'integer':
      return (
        <div>
          <label htmlFor={id} className="block text-sm font-medium text-dark-text mb-2">{label}</label>
          <input
            type="number"
            id={id}
            value={value ?? ''}
            onChange={(e) => onChange(section, field, e.target.value ? parseInt(e.target.value) : null)}
            className="input w-48"
          />
          <p className="mt-2 text-sm text-dark-text-secondary">{description}</p>
        </div>
      );

    case 'path':
      return (
        <PathInput
          id={id}
          label={label}
          value={value || ''}
          onChange={(v) => onChange(section, field, v)}
          type="directory"
          description={description}
        />
      );

    case 'url':
      return (
        <UrlInput
          id={id}
          label={label}
          value={value || ''}
          onChange={(v) => onChange(section, field, v)}
          description={description}
          placeholder="localhost:5000"
          defaultProtocol="http://"
          className="w-96"
        />
      );

    case 'enum':
      return (
        <div>
          <label htmlFor={id} className="block text-sm font-medium text-dark-text mb-2">{label}</label>
          <select
            id={id}
            value={value || ''}
            onChange={(e) => onChange(section, field, e.target.value)}
            className="input w-64"
          >
            {options?.map((opt) => (
              <option key={opt} value={opt}>{opt}</option>
            ))}
          </select>
          <p className="mt-2 text-sm text-dark-text-secondary">{description}</p>
        </div>
      );

    default: // string
      return (
        <div>
          <label htmlFor={id} className="block text-sm font-medium text-dark-text mb-2">{label}</label>
          <input
            type={sensitive ? 'password' : 'text'}
            id={id}
            value={value || ''}
            onChange={(e) => onChange(section, field, e.target.value || null)}
            className="input w-64"
          />
          <p className="mt-2 text-sm text-dark-text-secondary">{description}</p>
        </div>
      );
  }
}

// ===================================================================
// Section Components
// ===================================================================

interface LibraryProps {
  config: Config;
  onChange: (section: keyof Config, field: string, value: any) => void;
  showAdvanced?: boolean;
}

export function LibraryConfigSection({ config, onChange, showAdvanced = false }: LibraryProps) {
  const section = config.library;
  const grpScanningVisible = [
    isFieldVisible({  }, section, showAdvanced),
    isFieldVisible({  }, section, showAdvanced),
    isFieldVisible({  }, section, showAdvanced),
    isFieldVisible({  }, section, showAdvanced),
  ].some(Boolean);
  const grpImportingVisible = [
    isFieldVisible({  }, section, showAdvanced),
  ].some(Boolean);
  const grpFileOrganizationVisible = [
    isFieldVisible({  }, section, showAdvanced),
    isFieldVisible({  }, section, showAdvanced),
    isFieldVisible({  }, section, showAdvanced),
    isFieldVisible({ dependsOn: "normalize_featuring" }, section, showAdvanced),
  ].some(Boolean);
  return (
    <div className="space-y-6">
      <ConfigField
        section="library"
        field="path"
        value={section.path}
        onChange={onChange}
        type="path"
        description="Path to music library directory"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      {grpScanningVisible && <GroupHeader title="Scanning" />}
      <ConfigField
        section="library"
        field="watch"
        value={section.watch}
        onChange={onChange}
        type="boolean"
        description="Watch library directory for changes"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="auto_scan"
        value={section.auto_scan}
        onChange={onChange}
        type="boolean"
        description="Automatically scan library on interval"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="auto_scan_interval_mins"
        value={section.auto_scan_interval_mins}
        onChange={onChange}
        type="integer"
        description="Minutes between automatic scans"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="auto_scan_on_startup"
        value={section.auto_scan_on_startup}
        onChange={onChange}
        type="boolean"
        description="Scan library when application starts"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      {grpImportingVisible && <GroupHeader title="Importing" />}
      <ConfigField
        section="library"
        field="auto_upgrade_existing_albums"
        value={section.auto_upgrade_existing_albums}
        onChange={onChange}
        type="boolean"
        description="When an album already in your library is discovered, automatically monitor it for quality upgrades"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      {grpFileOrganizationVisible && <GroupHeader title="File Organization" />}
      <ConfigField
        section="library"
        field="path_format"
        value={section.path_format}
        onChange={onChange}
        type="string"
        description="Directory structure format for organizing files"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="file_format"
        value={section.file_format}
        onChange={onChange}
        type="string"
        description="File naming format"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="normalize_featuring"
        value={section.normalize_featuring}
        onChange={onChange}
        type="boolean"
        description="Normalize featuring artist format in track titles"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="library"
        field="normalize_featuring_to"
        value={section.normalize_featuring_to}
        onChange={onChange}
        type="string"
        description="Format to use for featuring artists"
        dependsOn="normalize_featuring"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
    </div>
  );
}

interface SystemProps {
  config: Config;
  onChange: (section: keyof Config, field: string, value: any) => void;
  showAdvanced?: boolean;
}

export function SystemConfigSection({ config, onChange, showAdvanced = false }: SystemProps) {
  const section = config.system;
  const grpPathsVisible = [
    isFieldVisible({ advanced: true }, section, showAdvanced),
    isFieldVisible({ advanced: true }, section, showAdvanced),
    isFieldVisible({ advanced: true }, section, showAdvanced),
  ].some(Boolean);
  return (
    <div className="space-y-6">
      <ConfigField
        section="system"
        field="watch_config_file"
        value={section.watch_config_file}
        onChange={onChange}
        type="boolean"
        description="Watch config file for changes and reload automatically"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="system"
        field="check_updates"
        value={section.check_updates}
        onChange={onChange}
        type="boolean"
        description="Periodically check GitHub for new Skema releases"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      {grpPathsVisible && <GroupHeader title="Paths" />}
      <ConfigField
        section="system"
        field="database_path"
        value={section.database_path}
        onChange={onChange}
        type="path"
        description="SQLite database file path (default: skema.db in data directory)"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="system"
        field="data_dir"
        value={section.data_dir}
        onChange={onChange}
        type="path"
        description="Data directory override (default: platform-specific)"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="system"
        field="cache_dir"
        value={section.cache_dir}
        onChange={onChange}
        type="path"
        description="Cache directory override (default: platform-specific)"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
    </div>
  );
}

interface ServerProps {
  config: Config;
  onChange: (section: keyof Config, field: string, value: any) => void;
  showAdvanced?: boolean;
}

export function ServerConfigSection({ config, onChange, showAdvanced = false }: ServerProps) {
  const section = config.server;
  const grpApiAccessVisible = [
    isFieldVisible({ advanced: true }, section, showAdvanced),
  ].some(Boolean);
  const grpAdvancedVisible = [
    isFieldVisible({ advanced: true }, section, showAdvanced),
    isFieldVisible({ advanced: true }, section, showAdvanced),
    isFieldVisible({ advanced: true }, section, showAdvanced),
  ].some(Boolean);
  return (
    <div className="space-y-6">
      <ConfigField
        section="server"
        field="host"
        value={section.host}
        onChange={onChange}
        type="string"
        description="Server bind address"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="server"
        field="port"
        value={section.port}
        onChange={onChange}
        type="integer"
        description="Server port"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="server"
        field="username"
        value={section.username}
        onChange={onChange}
        type="string"
        description="Username for API authentication (required)"
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      {grpApiAccessVisible && <GroupHeader title="API Access" />}
      <ConfigField
        section="server"
        field="api_key"
        value={section.api_key}
        onChange={onChange}
        type="string"
        description="API key for external access, sent via the X-API-Key header"
        sensitive
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      {grpAdvancedVisible && <GroupHeader title="Advanced" />}
      <ConfigField
        section="server"
        field="web_root"
        value={section.web_root}
        onChange={onChange}
        type="string"
        description="Web root path for hosting at subpaths (e.g., /skema or /)"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="server"
        field="jwt_secret"
        value={section.jwt_secret}
        onChange={onChange}
        type="string"
        description="JWT signing secret (auto-generated if not provided)"
        sensitive
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="server"
        field="jwt_expiration_hours"
        value={section.jwt_expiration_hours}
        onChange={onChange}
        type="integer"
        description="JWT token expiration time in hours"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
    </div>
  );
}

interface MusicbrainzProps {
  config: Config;
  onChange: (section: keyof Config, field: string, value: any) => void;
  showAdvanced?: boolean;
}

export function MusicbrainzConfigSection({ config, onChange, showAdvanced = false }: MusicbrainzProps) {
  const section = config.musicbrainz;
  const grpMatchingVisible = [
    isFieldVisible({ advanced: true }, section, showAdvanced),
    isFieldVisible({ advanced: true }, section, showAdvanced),
    isFieldVisible({ advanced: true }, section, showAdvanced),
  ].some(Boolean);
  return (
    <div className="space-y-6">
      <ConfigField
        section="musicbrainz"
        field="server"
        value={section.server}
        onChange={onChange}
        type="enum"
        description="Which MusicBrainz server to use"
        options={['official', 'headphones_vip', 'custom']}
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="musicbrainz"
        field="custom_url"
        value={section.custom_url}
        onChange={onChange}
        type="url"
        description="Custom MusicBrainz server URL (required if server is 'custom')"
        dependsOnValue={{ field: "server", values: ["custom"] }}
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="musicbrainz"
        field="username"
        value={section.username}
        onChange={onChange}
        type="string"
        description="Username for authentication (required for Headphones VIP, optional for custom)"
        dependsOnValue={{ field: "server", values: ["headphones_vip", "custom"] }}
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="musicbrainz"
        field="password"
        value={section.password}
        onChange={onChange}
        type="string"
        description="Password for authentication (required for Headphones VIP, optional for custom)"
        sensitive
        dependsOnValue={{ field: "server", values: ["headphones_vip", "custom"] }}
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      {grpMatchingVisible && <GroupHeader title="Matching" />}
      <ConfigField
        section="musicbrainz"
        field="match_min_confidence"
        value={section.match_min_confidence}
        onChange={onChange}
        type="integer"
        description="Minimum match confidence (%) required to auto-accept a MusicBrainz match"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="musicbrainz"
        field="max_candidates"
        value={section.max_candidates}
        onChange={onChange}
        type="integer"
        description="Maximum number of release candidates to consider per album"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
      <ConfigField
        section="musicbrainz"
        field="search_limit"
        value={section.search_limit}
        onChange={onChange}
        type="integer"
        description="Maximum number of releases to fetch from MusicBrainz search"
        advanced
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
    </div>
  );
}

interface MediaProps {
  config: Config;
  onChange: (section: keyof Config, field: string, value: any) => void;
  showAdvanced?: boolean;
}

export function MediaConfigSection({ config, onChange, showAdvanced = false }: MediaProps) {
  const section = config.media;
  return (
    <div className="space-y-6">
      <ConfigField
        section="media"
        field="lastfm_api_key"
        value={section.lastfm_api_key}
        onChange={onChange}
        type="string"
        description="Last.fm API key for artist images and scrobbling"
        sensitive
        showAdvanced={showAdvanced}
        sectionValues={section}
      />
    </div>
  );
}

// ConfigField/GroupHeader are not exported with 'export function', so export them here
export { ConfigField, GroupHeader };
